# Generated by Django 5.2.6 on 2025-10-13 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('cook_time', models.DurationField(blank=True, null=True)),
                ('prep_time', models.DurationField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='recipe_photos/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
