# Generated by Django 5.2.6 on 2025-10-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_category_ingredientsquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
